version: "3.9"
services:
  backend:
    container_name: starbridge-backend
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
  frontend:
    container_name: starbridge-frontend
    build:
      context: ./react-web
      dockerfile: Dockerfile
    volumes:
      - './react-web:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
  ccd-node-service:
    container_name: starbridge-ccd-node-service
    build:
      context: ./concordium-node-service
      dockerfile: Dockerfile
    volumes:
      - './concordium-node-service:/app'
      - '/app/node_modules'
    ports:
      - '8130:8130'