version: "3.9"
services:
  backend:
    container_name: starbridge-backend
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
  ccd-node-service:
    container_name: starbridge-ccd-node-service
    build:
      context: ./concordium-node-service
      dockerfile: Dockerfile
    volumes:
      - './concordium-node-service:/app'
      - '/app/node_modules'
    ports:
      - '8130:8130'