version: "3.9"
services:
  testnet-backend:
    container_name: starbridge-backend-testnet
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
  testnet-ccd-node-service:
    container_name: starbridge-ccd-node-service-testnet
    build:
      context: ./concordium-node-service
      dockerfile: Dockerfile
    volumes:
      - './concordium-node-service:/app'
      - '/app/node_modules'
    ports:
      - '8130:8130'
  mainnet-backend:
    container_name: starbridge-backend-mainnet
    build:
      context: .
      dockerfile: mainnet.Dockerfile
    network_mode: host
  mainnet-ccd-node-service:
    container_name: starbridge-ccd-node-service-mainnet
    build:
      context: ./concordium-node-service
      dockerfile: mainnet.Dockerfile
    volumes:
      - './concordium-node-service:/app'
      - '/app/node_modules'
    ports:
      - '8131:8130'